# Generated by Django 5.2.4 on 2025-08-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='public_link',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
